language: c

env:
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0

before_install:
  - OPAM_DEPENDS="ocamlgraph ocamlfind"
  - chmod +x ./.ocaml-config.sh
  - sudo -E ./.ocaml-config.sh
  - until sudo add-apt-repository -y ppa:saiarcot895/chromium-beta; do echo retry; done
   - until sudo add-apt-repository --yes ppa:kalakris/cmake; do echo retry; done
   - until sudo apt-get -qq update; do echo retry; done 
   - until sudo apt-get install cmake; do echo retry; done

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml opam
  - export OPAMYES=1
  - opam init
  - opam install ${OPAM_DEPENDS}
  - eval `opam config env`
  - export LZ="$TRAVIS_BUILD_DIR/../zustre"
  - git clone https://github.com/coco-team/zustre $LZ
  -ls $LZ

before_script:
  - ocaml -version
  - opam --version

script:
  - autoconf
  - ./configure
  - make
  - cd test
  - ./regression.sh -r -v 2 horn_regression.list



notifications:
  email:
    recipients:
     - lustrec-build@googlegroups.com
    on_success: always
    on_failure: always
